import { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { Minus, Plus, ArrowUpRight, Copy, Check, ShoppingBag } from 'lucide-react';
import { toast } from 'sonner';
import { useStore } from '../../context/StoreContext';
import { Modal, Action, OLink, Image } from './Common';
import { api, errorText, imgUrl } from '../../lib/api';

export const Checkout = ({items,disabled=false}) => {
  const {store,currency,preview}=useStore();const [notes,setNotes]=useState(''),[shipping,setShipping]=useState({name:'',phone:'',address:''}),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[copied,setCopied]=useState(false);
  const prepare=async()=>{if(preview){toast.info('Ordering is disabled in draft preview. Open the live store to order.');return;}setBusy(true);try{const {data}=await api.post('/orders/prepare',{items:items.map(({product_id,size,color,quantity})=>({product_id,size,color,quantity})),currency,notes,...shipping});setResult(data);}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
  const copy=async()=>{try{await navigator.clipboard.writeText(result.summary);setCopied(true);toast.success('Order summary copied.');}catch{toast.error('Copy isn’t available in this browser. Select the summary text instead.');}};
  if(!store.features.whatsapp||!store.checkout.whatsapp_enabled)return <p className="checkout-note" data-testid="checkout-disabled">Ordering is currently paused. <OLink to="/contact" data-testid="checkout-contact-disabled">Contact our team.</OLink></p>;
  return <div className="checkout-section">{store.checkout.notes_enabled&&<label className="note-field">A NOTE FOR US (OPTIONAL)<textarea data-testid="order-notes" rows="2" placeholder="Sizing questions, delivery details…" maxLength={1500} value={notes} onChange={e=>setNotes(e.target.value)}/></label>}{store.checkout.shipping_fields&&<div className="shipping-fields">{['name','phone','address'].map(key=><label key={key}>{key.toUpperCase()}<input data-testid={`order-${key}`} value={shipping[key]} onChange={e=>setShipping({...shipping,[key]:e.target.value})} maxLength={key==='address'?500:120}/></label>)}</div>}<Action className="full-width whatsapp-action" onClick={prepare} disabled={busy||disabled||!items.length} data-testid="prepare-whatsapp-order">{busy?'PREPARING YOUR ORDER…':'ORDER VIA WHATSAPP'}<ArrowUpRight size={17}/></Action><p className="checkout-note">No account. No complicated checkout.<br/>Review and send your order directly to our team.</p><Modal open={!!result} onOpenChange={o=>{if(!o)setResult(null);}} title="A conversation away." description="Your order summary is ready. This is an inquiry, not a confirmed order." testId="order-summary-modal" className="order-summary-modal">{result&&<><span className="eyebrow" data-testid="order-reference">{result.id}</span><pre className="order-summary-text" data-testid="order-summary-text" data-lenis-prevent>{result.summary}</pre>{result.whatsapp_url?<a className="action whatsapp-action" href={result.whatsapp_url} target="_blank" rel="noreferrer" data-testid="whatsapp-continue">CONTINUE TO WHATSAPP<ArrowUpRight size={17}/></a>:<div className="connection-notice" data-testid="whatsapp-unconfigured">WhatsApp ordering is not connected yet. Copy your summary and use our contact form to reach the team.<OLink to="/contact" data-testid="order-contact-fallback">CONTACT ORYNVE ↗</OLink></div>}<Action className="action-outline" onClick={copy} data-testid="copy-order-summary">{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'COPIED':'COPY ORDER SUMMARY'}</Action><p className="checkout-note">WhatsApp will open with your message prepared. You choose when to send it. Availability, delivery, and payment are confirmed by our team.</p></>}</Modal></div>;
};

export const Cart = () => {
  const {store,cart,setCart,cartOpen,setCartOpen,money,currency}=useStore();
  const location=useLocation();
  useEffect(()=>{setCartOpen(false);},[location.pathname,setCartOpen]);
  const detailed=cart.map(i=>({...i,product:store.products.find(p=>p.id===i.product_id)}));
  const total=detailed.reduce((a,i)=>a+(i.product?(i.product.sale_price??i.product.price)*i.quantity:0),0);
  const update=(key,quantity,max)=>{if(quantity<1)return; if(quantity>max){toast.error(`Only ${max} available.`);return;}setCart(prev=>prev.map(i=>i.key===key?{...i,quantity}:i));};
  return <Modal open={cartOpen} onOpenChange={setCartOpen} title={`Your bag (${cart.reduce((a,i)=>a+i.quantity,0)})`} description="Good pieces. Great choices." testId="cart-drawer" className="cart-drawer"><div className="cart-content" data-lenis-prevent>{!cart.length?<div className="empty-bag" data-testid="empty-cart"><ShoppingBag size={36} strokeWidth={1}/><h2>A little room for possibility.</h2><p>Your next constant is waiting.</p><OLink to="/shop" className="action" onClick={()=>setCartOpen(false)} data-testid="empty-cart-shop">EXPLORE THE COLLECTION<ArrowUpRight size={16}/></OLink></div>:<>{detailed.map(i=><div className="cart-item" key={i.key} data-testid={`cart-item-${i.key}`}>{i.product?<><OLink to={`/product/${i.product.slug}`} onClick={()=>setCartOpen(false)} data-testid={`cart-product-${i.key}`}><Image src={imgUrl(i.product.images[0],300)} alt={i.product.name}/></OLink><div className="cart-item-info"><span className="eyebrow">{i.product.category}</span><h2>{i.product.name}</h2><small>{i.color} / {i.size}</small><span data-testid={`cart-price-${i.key}`}>{money((i.product.sale_price??i.product.price)*i.quantity)}</span><div className="cart-quantity">{store.checkout.quantity_enabled&&<div className="quantity-control"><button aria-label="Decrease quantity" data-testid={`cart-minus-${i.key}`} disabled={i.quantity<=1} onClick={()=>update(i.key,i.quantity-1,20)}><Minus size={12}/></button><span data-testid={`cart-quantity-${i.key}`}>{i.quantity}</span><button aria-label="Increase quantity" data-testid={`cart-plus-${i.key}`} onClick={()=>update(i.key,i.quantity+1,i.product.sizes.find(s=>s.name===i.size)?.stock||0)}><Plus size={12}/></button></div>}<button className="remove-link" data-testid={`cart-remove-${i.key}`} onClick={()=>setCart(prev=>prev.filter(x=>x.key!==i.key))}>REMOVE</button></div></div></>:<div><p>This piece is no longer available.</p><button data-testid={`cart-remove-${i.key}`} onClick={()=>setCart(prev=>prev.filter(x=>x.key!==i.key))}>Remove item</button></div>}</div>)}<div className="cart-subtotal"><span>SUBTOTAL <small>({currency})</small></span><strong data-testid="cart-subtotal">{money(total)}</strong></div><p className="checkout-note">Delivery confirmed with your order.{currency!=='BDT'&&' Converted prices are estimates. Final payment is agreed in BDT.'}</p><Checkout items={cart} disabled={detailed.some(i=>!i.product)}/><button className="continue-shopping" onClick={()=>setCartOpen(false)} data-testid="continue-shopping">CONTINUE EXPLORING</button></>}</div></Modal>;
};