import { useEffect, useRef, useState } from 'react';
import { Search as SearchIcon, ArrowUpRight, X } from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import { Modal, OLink, Image } from './Common';
import { imgUrl } from '../../lib/api';

export const Search = () => {
  const {store,searchOpen,setSearchOpen,money}=useStore(); const [q,setQ]=useState(''),[active,setActive]=useState(-1);
  const [recent,setRecent]=useState(()=>{try{return JSON.parse(localStorage.getItem('orynve-searches'))||[];}catch{return[];}});const resultsRef=useRef(null);
  const term=q.trim().toLowerCase();const products=term?store.products.filter(p=>[p.name,p.category,p.description,p.collection,...(p.tags||[])].join(' ').toLowerCase().includes(term)):store.products.slice(0,4);
  const collections=term?store.collections.filter(c=>c.name.toLowerCase().includes(term)):[];
  useEffect(()=>{setActive(-1);},[q]);
  const close=()=>{if(term){const next=[q,...recent.filter(r=>r!==q)].slice(0,5);setRecent(next);localStorage.setItem('orynve-searches',JSON.stringify(next));}setSearchOpen(false);};
  const onKeys=e=>{const links=resultsRef.current?.querySelectorAll('a');if(!links?.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const next=e.key==='ArrowDown'?(active+1)%links.length:(active-1+links.length)%links.length;setActive(next);links[next].focus();}if(e.key==='Enter'&&active>=0){e.preventDefault();links[active].click();}};
  return <Modal open={searchOpen} onOpenChange={setSearchOpen} title="Find your next constant." className="search-modal" testId="search-modal"><div className="search-field"><SearchIcon size={24}/><input autoFocus data-testid="search-input" aria-label="Search products and collections" placeholder="Search pieces, collections, or a feeling…" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={onKeys}/>{q&&<button onClick={()=>setQ('')} aria-label="Clear search" data-testid="search-clear"><X size={18}/></button>}</div><div className="search-suggestions"><span className="eyebrow">{recent.length?'RECENT':'CONSIDER'}</span>{(recent.length?recent:[...new Set(store.products.map(p=>p.category))].slice(0,4)).map((s,i)=><button key={s} onClick={()=>setQ(s)} data-testid={`search-suggestion-${i}`}>{s}</button>)}{recent.length>0&&<button className="muted" onClick={()=>{setRecent([]);localStorage.removeItem('orynve-searches');}} data-testid="search-clear-recent">Clear history</button>}</div><div ref={resultsRef} onKeyDown={onKeys} className="search-results" data-lenis-prevent><span className="eyebrow" data-testid="search-result-count">{term?`${products.length} PIECES FOUND`:'THE CONSIDERED EDIT'}</span>{!products.length&&!collections.length&&<div className="search-empty" data-testid="search-empty">Nothing here, just yet.<p>Try a different word, like “shirt” or “outerwear”.</p></div>}<div className="search-product-grid">{products.map(p=><OLink to={`/product/${p.slug}`} key={p.id} onClick={close} data-testid={`search-result-${p.id}`}><Image src={imgUrl(p.images[0],400)} alt={p.name}/><span>{p.name}</span><small>{money(p.sale_price??p.price)}</small></OLink>)}</div>{collections.map(c=><OLink key={c.id} to={`/collections/${c.slug}`} onClick={close} className="search-collection" data-testid={`search-collection-${c.id}`}>{c.name}<span>COLLECTION <ArrowUpRight size={15}/></span></OLink>)}</div></Modal>;
};