def image(id, width=1400):
    return f'https://images.unsplash.com/{id}?auto=format&fit=crop&w={width}&q=90'

def initial_store():
    store = _build_initial_store()
    store['hero']['position'] = '50% 0%'
    for p in store['products']:
        if p['id'] in ('p003','p006'):
            p['collection'] = 'everyday-elevated'
        elif p['id'] in ('p004','p005'):
            p['collection'] = 'after-hours'
    return store

def _build_initial_store():
    coat = image('photo-1619603364904-c0498317e145')
    coat2 = image('photo-1619603364937-8d7af41ef206')
    shirt = image('photo-1732464517757-c47075f33821')
    white = image('photo-1529284607059-de6f2f0e661f')
    knit = image('photo-1760245773960-200dbe893696')
    tailoring = image('photo-1732464517792-7385024242a6')
    tee = image('photo-1706905615817-75a4a27867fa')
    campaign = image('photo-1603189343302-e603f7add05a',2000)
    details = [
        ('The Form Overcoat','the-form-overcoat',8900,'Outerwear','Sand', '#b09a82',coat,coat2,'A considered silhouette, cut to move. Our signature longline overcoat brings quiet structure to your everyday uniform.','Wool-blend outer; smooth viscose lining','Relaxed, longline fit. Designed for layering.','Dry clean only. Store on a wide hanger.'),
        ('The Ease Shirt','the-ease-shirt',3200,'Shirts','Onyx','#262521',shirt,shirt,'An easy drape. A deliberate detail. A soft, open-collar shirt that finds its place from first light to late nights.','Breathable cotton blend','Relaxed fit with a dropped shoulder.','Machine wash cold. Line dry in shade.'),
        ('The Essential Oxford','the-essential-oxford',3600,'Shirts','Chalk','#ebe8e0',white,white,'The shirt you return to. Clean lines, a refined collar, and natural texture, made for a wardrobe without seasons.','100% cotton Oxford weave','Regular fit. Take your usual size.','Wash at 30°C with similar colors. Warm iron.'),
        ('The Midnight Knit','the-midnight-knit',4900,'Knitwear','Black','#171817',knit,knit,'A study in restraint. Fine-gauge texture and a clean crew neckline make a subtle statement in deep black.','Soft cotton-rich knit','Close regular fit with comfortable stretch.','Hand wash cold. Reshape and dry flat.'),
        ('The Unstructured Blazer','the-unstructured-blazer',7500,'Tailoring','Graphite','#575754',tailoring,tailoring,'Tailoring, untethered. A lightly structured blazer designed to dress up without the weight of occasion.','Textured wool-blend suiting','Relaxed through the shoulder and body.','Professional dry clean only.'),
        ('The Everyday Tee','the-everyday-tee',1800,'Essentials','Ecru','#ddd8ca',tee,tee,'Nothing extra. Everything considered. A substantial cotton tee with a softly structured silhouette.','100% heavyweight cotton','Boxy fit. Size down for a closer silhouette.','Cold machine wash. Do not tumble dry.')
    ]
    products=[]
    for i,(name,slug,price,category,color,hexcode,img,img2,desc,material,fit,care) in enumerate(details):
        products.append({'id':f'p{i+1:03}', 'name':name, 'slug':slug, 'price':price, 'sale_price':None, 'sku':f'ORY-001-{i+1:03}', 'category':category, 'collection':'the-first-expression', 'tags':['new','essential'], 'status':'published', 'featured':i<4, 'badge':'SIGNATURE' if i==0 else 'NEW SEASON', 'description':desc, 'material':material, 'fit':fit, 'care':care, 'shipping':'Delivery within Bangladesh in 3–7 business days. Shipping cost confirmed before your order is finalized on WhatsApp.', 'returns':'Request an exchange within 7 days of delivery. Items must be unworn, with original tags. Contact our team before returning.', 'colors':[{'name':color,'hex':hexcode}], 'sizes':[{'name':s,'stock':n} for s,n in [('XS',0),('S',6),('M',10),('L',3),('XL',5),('XXL',0)]], 'images':list(dict.fromkeys([img,img2])), 'video':'', 'image_alt':f'{name} in {color}, menswear editorial', 'focal_point':'50% 35%', 'size_guide':{'unit':'cm','labels':['Size','Chest','Length','Shoulder'], 'rows':[['XS','96','68','43'],['S','100','70','45'],['M','104','72','47'],['L','110','74','49'],['XL','116','76','51'],['XXL','122','78','53']], 'notes':'Garment measurements, laid flat. Allow 1–2 cm tolerance. If between sizes, choose the larger size for an easier fit.'}, 'seo_title':f'{name} | ORYNVE', 'seo_description':desc})
    pages=[
        ('about','A different kind of presence.','We believe the most powerful thing you can wear is a sense of yourself.\n\nORYNVE is an independent menswear label exploring the space between refined and unconventional. Considered silhouettes. Honest materials. Pieces that feel as good as they look.\n\nWe create for those who don’t need to be the loudest in the room. Clothing with intention. Style without explanation.'),
        ('shipping','Delivery, considered.','We currently deliver throughout Bangladesh. Standard delivery usually takes 3–7 business days after order confirmation.\n\nDelivery charges and the final total will be confirmed by our team on WhatsApp before you place your order. International delivery can be discussed with our team. Currency conversions are estimates; final payment is agreed in BDT.'),
        ('returns','A better fit.','If something isn’t quite right, contact us within 7 days of receiving your item to request an exchange.\n\nItems must be unworn, unwashed, and returned with their original tags and packaging. Our team will confirm eligibility and guide you through the next steps. Please do not send items back before speaking with us.'),
        ('size-guide','Find your form.','Our pieces are designed with a considered, modern fit. Each product includes a dedicated size chart and fit notes.\n\nMeasure a similar garment you already love and compare it to the chart. Chest measurements refer to the garment circumference. If you prefer a relaxed silhouette, choose the larger size when between sizes.\n\nNeed a second opinion? Contact the ORYNVE team for personal sizing guidance.'),
        ('faq','Good questions.','HOW DO I ORDER?\nChoose your pieces, select your size, and add them to your bag. Order via WhatsApp prepares a complete summary for you to review and send. Our team then confirms availability, delivery, and payment.\n\nDO I NEED AN ACCOUNT?\nNo. Your wardrobe should be effortless. Browse and order without creating an account.\n\nIS MY ORDER CONFIRMED ON THE WEBSITE?\nNo. Opening WhatsApp prepares your message; it does not send it or confirm an order. Our team confirms your order directly.\n\nCAN I CHANGE MY ORDER?\nContact us as soon as possible. We’ll help where we can before dispatch.'),
        ('privacy','Your privacy matters.','We collect the information you choose to share through inquiries and newsletter subscriptions. Your shopping bag and currency preference are stored locally on your device.\n\nOwner authentication uses secure cookies. We do not create customer accounts or collect payment card details. When you continue to WhatsApp, its own privacy policy applies.\n\nContact us to request access to or deletion of your information.'),
        ('terms','A few considered details.','Product availability and prices are confirmed by our team before accepting your order. Displayed currency conversions are indicative; our base currency is BDT.\n\nWebsite order summaries are inquiries, not completed purchases. A purchase is confirmed only after our team agrees on the items, delivery, and payment with you.\n\nPhotography and screen settings may cause colors to appear slightly different. For fit and materials, consult the product details and contact our team if you need clarification.')
    ]
    return {'brand':{'name':'ORYNVE','tagline':'Not for everyone. For you.','accent':'#a95035','theme':'light','font':'Manrope','spacing':'generous','border_style':'sharp'},
        'hero':{'eyebrow':'COLLECTION 001 / THE FIRST EXPRESSION','headline':'Quiet\nrebellion.','subheadline':'Not made to fit in.\nMade to feel like you.','image':coat,'video':'','position':'50% 32%','overlay':0.22,'cta':'SHOP THE COLLECTION','cta_link':'/shop','secondary':'DISCOVER ORYNVE','secondary_link':'/about','caption':'A STUDY IN FORM. A SHIFT IN PERSPECTIVE.','animation':True},
        'sections':[{'id':'s1','type':'featured','title':'The considered edit.','subtitle':'Less, but with intention. Meet your new constants.','enabled':True}, {'id':'s2','type':'editorial','title':'Presence.\nWithout the noise.','subtitle':'For the ones who move differently. Who see beauty in the unassuming. Who know that less isn’t a compromise — it’s a point of view.','image':campaign,'link':'/about','button':'OUR PHILOSOPHY','enabled':True}, {'id':'s3','type':'lookbook','title':'Between the lines.','subtitle':'THE FIRST EXPRESSION — CAMPAIGN 001','image':coat2,'image2':shirt,'product_ids':['p001','p002'],'enabled':True}, {'id':'s4','type':'arrivals','title':'New perspective.','subtitle':'Fresh forms. Familiar feeling.','enabled':True}, {'id':'s5','type':'manifesto','title':'Not for everyone.\nFor you.','subtitle':'We don’t dress the moment. We dress the individual. Considered menswear for a life that’s entirely your own.','enabled':True}],
        'products':products,
        'collections':[{'id':'c1','name':'The First Expression','slug':'the-first-expression','description':'Our debut chapter. A study in form, texture, and quiet confidence.','image':coat2,'published':True}, {'id':'c2','name':'Everyday, Elevated','slug':'everyday-elevated','description':'A considered edit of the pieces you reach for, again and again.','image':shirt,'published':True}, {'id':'c3','name':'After Hours','slug':'after-hours','description':'Refined silhouettes for wherever the evening takes you.','image':tailoring,'published':True}],
        'navigation':[{'id':'n1','label':'Shop','href':'/shop'},{'id':'n2','label':'Collections','href':'/collections'},{'id':'n3','label':'New Arrivals','href':'/shop?sort=new'},{'id':'n4','label':'Lookbook','href':'/lookbook'},{'id':'n5','label':'About','href':'/about'}],
        'footer':{'statement':'Independent in spirit.\nConsidered by design.','copyright':'© 2026 ORYNVE. All rights reserved.','groups':[{'id':'f1','title':'EXPLORE','links':[{'label':'All pieces','href':'/shop'},{'label':'Collections','href':'/collections'},{'label':'Our story','href':'/about'},{'label':'Lookbook','href':'/lookbook'}]},{'id':'f2','title':'CLIENT SERVICES','links':[{'label':'Contact','href':'/contact'},{'label':'Shipping & delivery','href':'/shipping'},{'label':'Returns & exchanges','href':'/returns'},{'label':'Size guide','href':'/size-guide'},{'label':'FAQ','href':'/faq'}]},{'id':'f3','title':'THE DETAILS','links':[{'label':'Privacy policy','href':'/privacy'},{'label':'Terms of service','href':'/terms'}]}]},
        'contact':{'whatsapp':'','email':'','phone':'','address':'Dhaka, Bangladesh','hours':'Sunday–Thursday, 10:00–18:00 BST','text':'A conversation, not a checkout.','whatsapp_enabled':True,'email_enabled':False,'form_enabled':True,'chat_enabled':False,'chat_url':'','chat_provider':'','floating_position':'right','floating_text':'LET’S TALK','socials':[]},
        'checkout':{'whatsapp_enabled':True,'notes_enabled':True,'shipping_fields':False,'quantity_enabled':True,'product_link':True,'order_identifier':True,'instructions':'Our team will confirm availability, delivery and payment on WhatsApp.'},
        'features':{'search':True,'cart':True,'whatsapp':True,'newsletter':True,'wishlist':True,'quick_view':True,'quick_add':True,'product_video':True,'announcement':True,'cursor':True,'transitions':True,'preloader':True,'animations':True},
        'announcement':{'text':'A new expression of everyday. Discover Collection 001.','link':'/shop'},
        'newsletter':{'title':'Stay in the know.','text':'New collections. Quiet inspiration. Only when it matters.','consent':'By subscribing, you agree to our privacy policy.'},
        'currencies':[{'code':'BDT','symbol':'৳','rate':1,'enabled':True},{'code':'USD','symbol':'$','rate':0.0082,'enabled':True},{'code':'EUR','symbol':'€','rate':0.0075,'enabled':True},{'code':'GBP','symbol':'£','rate':0.0064,'enabled':True}],
        'site_mode':'live','maintenance':{'title':'Something considered\nis on its way.','message':'We’re taking a moment to make things even better. Be the first to know when we return.','image':campaign,'launch_date':'','button':'GET IN TOUCH','link':'/contact'},
        'pages':[{'id':f'pg{i}','slug':slug,'title':title,'body':body,'published':True,'seo_title':f'{title} | ORYNVE','seo_description':body[:155]} for i,(slug,title,body) in enumerate(pages)],
        'seo':{'title':'ORYNVE — Quiet rebellion. Considered menswear.','description':'Independent in spirit. Considered by design. Discover refined menswear, modern silhouettes and Collection 001 by ORYNVE.','image':coat}}