/**
 * Built-in themes. Each preset is a complete `ThemeDefinition`: three token maps
 * (light / dark / true-black), its own typography and its own layout choices.
 *
 * ── Contrast guarantee ───────────────────────────────────────────────────────
 * Every palette below satisfies, in all three modes (see `auditTokens()` in
 * ./contrast.ts for the exact rules):
 *   ink on paper ≥ 7:1 · muted on paper/bone ≥ 4.5:1 ·
 *   accent on paper/bone ≥ 4.5:1 · snow-or-coal on accent ≥ 4.5:1
 * The palettes were generated by pushing each draft hue toward black (light
 * modes) or white (dark modes) in 3 % steps until every rule cleared, so the
 * numbers are the *corrected* values — edit them with `auditTokens()` in hand.
 *
 * `orynve` is byte-for-byte the palette shipped in globals.css, so a store with
 * no theme row and default settings renders exactly as before.
 */
import {
  BASE_BLACK,
  BASE_DARK,
  BASE_LIGHT,
  DEFAULT_LAYOUT,
  DEFAULT_TYPOGRAPHY,
  type ThemeDefinition,
  type ThemeLayout,
  type ThemeTypography,
  type TokenMap,
} from "./types";
import { toHex } from "./contrast";

const layout = (over: Partial<ThemeLayout> = {}): ThemeLayout => ({ ...DEFAULT_LAYOUT, ...over });
const type = (over: Partial<ThemeTypography> = {}): ThemeTypography => ({ ...DEFAULT_TYPOGRAPHY, ...over, customFonts: over.customFonts ?? [] });

/* ─────────────────────────── ORYNVE (shipped default) ───────────────────────────
   These three maps must stay identical to :root / [data-theme="dark"] in
   globals.css. `olive` is not re-declared in the dark block there, so it keeps
   the light value — reproduced faithfully here. */
const ORYNVE_LIGHT: TokenMap = { ink: "14 15 12", paper: "250 248 243", bone: "243 239 230", line: "216 211 199", muted: "104 99 90", oxide: "178 74 36", brass: "201 162 92", olive: "62 68 50", success: "46 125 75", danger: "185 52 43", warning: "150 98 18", elev: "255 255 255" };
const ORYNVE_DARK: TokenMap = { ink: "243 239 230", paper: "14 15 12", bone: "22 23 20", line: "52 53 48", muted: "168 166 158", oxide: "214 104 62", brass: "214 178 110", olive: "62 68 50", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "22 23 20" };
const ORYNVE_BLACK: TokenMap = { ...ORYNVE_DARK, paper: "0 0 0", bone: "12 12 12", line: "38 38 38", elev: "18 18 18" };

export const PRESETS: Record<string, ThemeDefinition> = {
  orynve: {
    key: "orynve",
    name: "ORYNVE",
    description: "The house look — warm bone paper, oxide accent, Fraunces display.",
    light: ORYNVE_LIGHT,
    dark: ORYNVE_DARK,
    black: ORYNVE_BLACK,
    typography: type(),
    layout: layout(),
    customCss: "",
  },

  ivory: {
    key: "ivory",
    name: "Ivory",
    description: "Gallery white with graphite type. Centred header, airy grid, no grain.",
    light: { ink: "22 24 26", paper: "255 255 255", bone: "244 244 242", line: "222 222 218", muted: "107 111 115", oxide: "68 80 99", brass: "138 124 98", olive: "74 83 72", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "236 238 239", paper: "18 20 21", bone: "27 30 32", line: "51 55 58", muted: "168 173 177", oxide: "159 179 205", brass: "199 183 154", olive: "144 160 140", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "41 44 45" },
    black: { ink: "236 238 239", paper: "0 0 0", bone: "14 15 16", line: "51 55 58", muted: "168 173 177", oxide: "159 179 205", brass: "199 183 154", olive: "144 160 140", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "28 29 30" },
    typography: type({ display: "Instrument Serif", sans: "Inter", bangla: "Hind Siliguri", scale: 1.05 }),
    layout: layout({ header: "centered", menu: "dropdown", footer: "columns", container: "wide", productGrid: 3, cardStyle: "minimal", radius: 0, density: "airy", grain: false }),
    customCss: "",
  },

  noir: {
    key: "noir",
    name: "Noir",
    description: "Charcoal editorial, dark by default. Overlay cards, crimson accent.",
    light: { ink: "18 18 18", paper: "247 247 245", bone: "235 235 232", line: "212 212 208", muted: "102 102 99", oxide: "138 34 48", brass: "141 115 80", olive: "69 72 61", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "240 239 236", paper: "20 20 20", bone: "29 29 29", line: "58 58 58", muted: "165 165 161", oxide: "232 116 127", brass: "203 174 134", olive: "158 160 140", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "43 43 43" },
    black: { ink: "240 239 236", paper: "0 0 0", bone: "12 12 12", line: "44 44 44", muted: "165 165 161", oxide: "232 116 127", brass: "203 174 134", olive: "158 160 140", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "27 27 27" },
    typography: type({ display: "Playfair Display", sans: "Archivo", bangla: "Noto Serif Bengali" }),
    layout: layout({ header: "classic", menu: "mega", footer: "editorial", cardStyle: "overlay", radius: 0, grain: true }),
    customCss: "",
  },

  sand: {
    key: "sand",
    name: "Sand",
    description: "Desert neutrals and terracotta. Utility header, bordered cards.",
    light: { ink: "42 33 24", paper: "250 245 236", bone: "240 231 216", line: "221 208 186", muted: "112 101 82", oxide: "168 75 44", brass: "143 106 42", olive: "107 106 69", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "242 233 217", paper: "25 21 16", bone: "34 29 22", line: "61 54 43", muted: "176 163 144", oxide: "232 154 114", brass: "216 180 120", olive: "163 160 116", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "47 43 36" },
    black: { ink: "242 233 217", paper: "0 0 0", bone: "17 15 11", line: "61 54 43", muted: "176 163 144", oxide: "232 154 114", brass: "216 180 120", olive: "163 160 116", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "31 29 26" },
    typography: type({ display: "Fraunces", sans: "Karla", bangla: "Hind Siliguri" }),
    layout: layout({ header: "utility", menu: "dropdown", footer: "columns", productGrid: 3, cardStyle: "bordered", buttonStyle: "rounded", radius: 6 }),
    customCss: "",
  },

  forest: {
    key: "forest",
    name: "Forest",
    description: "Deep green on cream with a Garamond display. Narrow, unhurried pages.",
    light: { ink: "22 33 26", paper: "247 244 234", bone: "234 230 216", line: "210 205 185", muted: "93 100 89", oxide: "31 92 61", brass: "138 111 51", olive: "61 90 58", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "236 234 221", paper: "15 21 18", bone: "23 32 26", line: "47 59 49", muted: "163 171 160", oxide: "105 200 146", brass: "207 180 126", olive: "139 176 138", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "37 45 40" },
    black: { ink: "236 234 221", paper: "0 0 0", bone: "12 16 13", line: "47 59 49", muted: "163 171 160", oxide: "105 200 146", brass: "207 180 126", olive: "139 176 138", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "27 30 28" },
    typography: type({ display: "Cormorant Garamond", sans: "DM Sans", bangla: "Tiro Bangla", scale: 1.1 }),
    layout: layout({ container: "narrow", productGrid: 3, buttonStyle: "rounded", radius: 4, density: "airy", grain: false }),
    customCss: "",
  },

  midnight: {
    key: "midnight",
    name: "Midnight",
    description: "Navy and brass, split header, wide grid. Quietly formal.",
    light: { ink: "16 26 43", paper: "246 247 250", bone: "232 235 241", line: "207 213 224", muted: "91 100 118", oxide: "29 63 122", brass: "127 99 32", olive: "63 79 86", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "231 236 245", paper: "10 15 26", bone: "18 26 42", line: "40 51 74", muted: "154 165 186", oxide: "140 176 238", brass: "212 179 106", olive: "143 169 181", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "32 40 55" },
    black: { ink: "231 236 245", paper: "0 0 0", bone: "9 13 21", line: "40 51 74", muted: "154 165 186", oxide: "140 176 238", brass: "212 179 106", olive: "143 169 181", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "24 28 35" },
    typography: type({ display: "Playfair Display", sans: "Manrope", bangla: "Anek Bangla" }),
    layout: layout({ header: "split", menu: "dropdown", footer: "columns", container: "wide", cardStyle: "bordered" }),
    customCss: "",
  },

  terminal: {
    key: "terminal",
    name: "Terminal",
    description: "Monospace everything, phosphor green, black first. Compact and fast.",
    light: { ink: "13 20 16", paper: "242 245 242", bone: "228 234 228", line: "200 210 200", muted: "87 100 90", oxide: "23 102 58", brass: "95 98 36", olive: "47 74 53", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "216 245 223", paper: "6 17 10", bone: "12 26 17", line: "32 54 39", muted: "143 184 156", oxide: "74 230 145", brass: "203 224 106", olive: "116 198 146", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "27 40 31" },
    black: { ink: "216 245 223", paper: "0 0 0", bone: "5 13 8", line: "20 48 30", muted: "143 184 156", oxide: "74 230 145", brass: "203 224 106", olive: "116 198 146", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "20 28 23" },
    typography: type({ display: "IBM Plex Mono", sans: "IBM Plex Mono", bangla: "Hind Siliguri", scale: 0.9 }),
    layout: layout({ header: "utility", menu: "inline", footer: "compact", container: "wide", cardStyle: "minimal", radius: 0, motion: "reduced", density: "compact", grain: false }),
    customCss: "",
  },

  bauhaus: {
    key: "bauhaus",
    name: "Bauhaus",
    description: "Primary red, yellow and blue on pure white. Geometric, hard edges.",
    light: { ink: "17 17 17", paper: "255 255 255", bone: "242 242 242", line: "216 216 216", muted: "95 95 95", oxide: "200 29 37", brass: "138 99 0", olive: "27 70 180", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "244 244 244", paper: "16 16 16", bone: "25 25 25", line: "53 53 53", muted: "166 166 166", oxide: "255 107 107", brass: "247 197 61", olive: "127 160 255", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "39 39 39" },
    black: { ink: "244 244 244", paper: "0 0 0", bone: "13 13 13", line: "53 53 53", muted: "166 166 166", oxide: "255 107 107", brass: "247 197 61", olive: "127 160 255", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "28 28 28" },
    typography: type({ display: "Archivo", sans: "Archivo", bangla: "Anek Bangla" }),
    layout: layout({ header: "split", menu: "dropdown", footer: "columns", container: "wide", productGrid: 3, cardStyle: "bordered", buttonStyle: "square", radius: 0, grain: false }),
    customCss: "",
  },

  linen: {
    key: "linen",
    name: "Linen",
    description: "Soft warm greys with an indigo accent. Rounded, roomy, gentle.",
    light: { ink: "34 33 31", paper: "249 248 245", bone: "238 236 231", line: "217 214 207", muted: "106 103 95", oxide: "64 64 156", brass: "138 116 64", olive: "85 88 76", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "239 236 229", paper: "23 22 20", bone: "32 31 28", line: "58 56 47", muted: "170 166 157", oxide: "166 166 242", brass: "204 182 132", olive: "155 160 136", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "45 44 42" },
    black: { ink: "239 236 229", paper: "0 0 0", bone: "16 16 14", line: "58 56 47", muted: "170 166 157", oxide: "166 166 242", brass: "204 182 132", olive: "155 160 136", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "30 30 28" },
    typography: type({ display: "Newsreader", sans: "Inter", bangla: "Hind Siliguri", scale: 1.02 }),
    layout: layout({ menu: "dropdown", footer: "columns", productGrid: 3, cardStyle: "minimal", buttonStyle: "rounded", radius: 8, density: "airy", grain: false }),
    customCss: "",
  },

  eid: {
    key: "eid",
    name: "Eid",
    description: "Festive emerald and gold with pill buttons. Made for campaign windows.",
    light: { ink: "16 33 26", paper: "251 248 240", bone: "241 234 217", line: "222 211 187", muted: "95 102 91", oxide: "6 103 74", brass: "133 99 23", olive: "60 90 69", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "243 238 224", paper: "12 20 16", bone: "19 32 26", line: "44 60 50", muted: "164 173 159", oxide: "79 210 162", brass: "224 190 94", olive: "143 189 159", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "33 45 40" },
    black: { ink: "243 238 224", paper: "0 0 0", bone: "10 16 13", line: "44 60 50", muted: "164 173 159", oxide: "79 210 162", brass: "224 190 94", olive: "143 189 159", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "25 30 28" },
    typography: type({ display: "Cormorant Garamond", sans: "Manrope", bangla: "Noto Serif Bengali", scale: 1.08 }),
    layout: layout({ header: "centered", productGrid: 3, buttonStyle: "pill", radius: 18 }),
    customCss: "",
  },

  monsoon: {
    key: "monsoon",
    name: "Monsoon",
    description: "Slate blue and rain grey. Drawer menu, minimal footer, quiet cards.",
    light: { ink: "23 28 33", paper: "245 247 248", bone: "231 235 238", line: "204 211 216", muted: "90 100 107", oxide: "42 95 122", brass: "115 108 92", olive: "70 90 84", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "233 238 241", paper: "16 22 26", bone: "23 31 36", line: "45 57 64", muted: "159 171 178", oxide: "124 194 226", brass: "194 187 166", olive: "147 180 172", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "37 44 49" },
    black: { ink: "233 238 241", paper: "0 0 0", bone: "12 16 18", line: "45 57 64", muted: "159 171 178", oxide: "124 194 226", brass: "194 187 166", olive: "147 180 172", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "27 30 32" },
    typography: type({ display: "Libre Baskerville", sans: "Karla", bangla: "Hind Siliguri", scale: 0.98 }),
    layout: layout({ menu: "drawer", footer: "minimal", cardStyle: "minimal", buttonStyle: "rounded", radius: 4 }),
    customCss: "",
  },

  neon: {
    key: "neon",
    name: "Neon",
    description: "Near-black canvas, electric violet accent, transparent header, overlay cards.",
    light: { ink: "11 11 15", paper: "244 244 247", bone: "230 230 236", line: "203 203 212", muted: "87 87 100", oxide: "106 31 208", brass: "140 47 154", olive: "47 74 107", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "236 234 245", paper: "7 7 11", bone: "14 14 20", line: "38 38 47", muted: "162 160 180", oxide: "196 155 255", brass: "255 143 223", olive: "143 178 232", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "28 28 34" },
    black: { ink: "236 234 245", paper: "0 0 0", bone: "7 7 11", line: "42 42 54", muted: "162 160 180", oxide: "196 155 255", brass: "255 143 223", olive: "143 178 232", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "22 22 26" },
    typography: type({ display: "Syne", sans: "Space Grotesk", bangla: "Anek Bangla", scale: 1.05 }),
    layout: layout({ header: "transparent", menu: "drawer", footer: "compact", container: "full", cardStyle: "overlay", buttonStyle: "pill", radius: 24, density: "compact" }),
    customCss: "",
  },

  paper: {
    key: "paper",
    name: "Paper",
    description: "Newsprint: serif body, serif headlines, inline nav, narrow measure.",
    light: { ink: "26 26 24", paper: "246 244 239", bone: "234 231 223", line: "211 207 196", muted: "99 96 90", oxide: "138 47 30", brass: "135 112 63", olive: "77 80 68", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "234 231 221", paper: "21 20 15", bone: "30 29 23", line: "57 55 46", muted: "168 164 154", oxide: "224 138 110", brass: "201 173 120", olive: "155 158 132", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "44 43 37" },
    black: { ink: "234 231 221", paper: "0 0 0", bone: "15 15 12", line: "57 55 46", muted: "168 164 154", oxide: "224 138 110", brass: "201 173 120", olive: "155 158 132", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "29 29 27" },
    typography: type({ display: "Libre Baskerville", sans: "Libre Baskerville", bangla: "Noto Serif Bengali", scale: 0.95 }),
    layout: layout({ header: "utility", menu: "inline", footer: "columns", container: "narrow", productGrid: 3, cardStyle: "bordered", radius: 0, motion: "reduced", density: "compact", grain: false, uppercaseEyebrows: false }),
    customCss: "",
  },

  atelier: {
    key: "atelier",
    name: "Atelier",
    description: "Rose-beige with oxblood. Centred header, generous margins, soft corners.",
    light: { ink: "36 27 28", paper: "250 244 241", bone: "240 228 222", line: "221 202 194", muted: "111 95 93", oxide: "122 34 48", brass: "150 103 74", olive: "94 83 72", success: "46 125 75", danger: "185 52 43", warning: "150 98 15", elev: "255 255 255" },
    dark: { ink: "243 232 227", paper: "26 19 21", bone: "35 25 27", line: "62 48 50", muted: "179 156 152", oxide: "236 144 158", brass: "213 168 136", olive: "169 154 145", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "48 39 41" },
    black: { ink: "243 232 227", paper: "0 0 0", bone: "18 13 14", line: "62 48 50", muted: "179 156 152", oxide: "236 144 158", brass: "213 168 136", olive: "169 154 145", success: "76 175 110", danger: "232 96 84", warning: "224 170 60", elev: "32 28 28" },
    typography: type({ display: "Cormorant Garamond", sans: "Karla", bangla: "Tiro Bangla", scale: 1.1 }),
    layout: layout({ header: "centered", container: "narrow", productGrid: 3, buttonStyle: "rounded", radius: 12, density: "airy", grain: false, uppercaseEyebrows: false }),
    customCss: "",
  },
};

export type PresetKey = keyof typeof PRESETS;

/** Ordered gallery entries for the studio preset picker. */
export type PresetSummary = {
  key: string;
  name: string;
  description: string;
  /** [paper, ink, accent, brass] as hex — enough for a four-chip swatch. */
  swatches: [string, string, string, string];
  header: ThemeLayout["header"];
  footer: ThemeLayout["footer"];
  display: string;
  sans: string;
};

const ORDER = ["orynve", "ivory", "noir", "sand", "forest", "midnight", "linen", "atelier", "paper", "monsoon", "eid", "bauhaus", "terminal", "neon"] as const;

export const PRESET_LIST: PresetSummary[] = ORDER.map((key) => {
  const p = PRESETS[key];
  return {
    key,
    name: p.name,
    description: p.description,
    swatches: [toHex(p.light.paper), toHex(p.light.ink), toHex(p.light.oxide), toHex(p.light.brass)] as [string, string, string, string],
    header: p.layout.header,
    footer: p.layout.footer,
    display: p.typography.display,
    sans: p.typography.sans,
  };
});

export const PRESET_KEYS: string[] = PRESET_LIST.map((p) => p.key);

/** Safe lookup — unknown keys fall back to the house preset. */
export function getPreset(key: string | null | undefined): ThemeDefinition {
  return (key && PRESETS[key]) || PRESETS.orynve;
}

/** Fill any missing token so a partial map can never break the emitted CSS. */
export function withBaseTokens(mode: "light" | "dark" | "black", tokens?: Partial<TokenMap> | null): TokenMap {
  const base = mode === "light" ? BASE_LIGHT : mode === "dark" ? BASE_DARK : BASE_BLACK;
  return { ...base, ...(tokens ?? {}) };
}
