import { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { ArrowUpRight, Check } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { SEO, OLink, Image, Reveal, EmptyState, Action } from '../components/store/Common';
import { Newsletter } from '../components/store/Layout';
import { LookbookSection } from './Home';
import { api, errorText, imgUrl } from '../lib/api';
import { toast } from 'sonner';

export const Collections = () => {const {store}=useStore();return <div className="collections-page section-pad"><SEO title="Collections | ORYNVE"/><span className="eyebrow">AN ONGOING EXPRESSION</span><h1 className="page-title" data-testid="collections-title">Chapters, not seasons.</h1><p className="page-intro">Each collection, a new perspective. The same independent spirit.</p><div className="collections-grid">{store.collections.map((c,i)=><Reveal key={c.id} delay={i*.1}><OLink to={`/collections/${c.slug}`} className="collection-card" data-testid={`collection-${c.id}`} data-cursor="EXPLORE"><div><Image src={imgUrl(c.image,1000)} alt={c.name} loading="lazy"/><span className="collection-number">0{i+1}</span></div><h2>{c.name}<ArrowUpRight size={25}/></h2><p>{c.description}</p></OLink></Reveal>)}</div></div>;};

export const Lookbook = () => {const {store}=useStore();const s=store.sections.find(s=>s.type==='lookbook'&&s.enabled);return <><SEO title="The Lookbook | ORYNVE"/><div className="lookbook-page-heading section-pad"><span className="eyebrow">THE FIRST EXPRESSION / CAMPAIGN 001</span><h1 className="page-title" data-testid="lookbook-title">A different point of view.</h1><p className="page-intro">Clothing in context. Discover the collection, one frame at a time.</p></div>{s?<LookbookSection section={s} full/>:<EmptyState title="The next chapter is coming." text="Our next campaign will be here soon."/>}</>;};

export const ContentPage = () => {
  const {store}=useStore(),location=useLocation(),slug=location.pathname.replace(/^\//,'');const p=store.pages.find(p=>p.slug===slug);const editorial=store.sections.find(s=>s.type==='editorial');
  if(!p)return <EmptyState title="A little off the beaten path." text="This page could not be found. Let’s find your way back." link="/" label="BACK TO ORYNVE" testId="page-not-found"/>;
  return <><SEO title={p.seo_title||`${p.title} | ORYNVE`} description={p.seo_description}/><div className={`content-page section-pad ${slug==='about'?'about-page':''}`}><Reveal><span className="eyebrow">{slug==='about'?'THE ORYNVE PHILOSOPHY':'CLIENT SERVICES / ORYNVE'}</span><h1 className="page-title" data-testid="content-page-title">{p.title}</h1></Reveal><div className="content-body-layout">{slug==='about'&&editorial&&<Reveal className="about-image"><Image src={imgUrl(editorial.image,1400)} alt="ORYNVE — an independent expression"/></Reveal>}<Reveal className="content-body"><div data-testid="content-page-body">{p.body.split('\n\n').map((para,i)=><p key={i}>{para}</p>)}</div><OLink to={slug==='about'?'/shop':'/contact'} className="text-link" data-testid="content-page-cta">{slug==='about'?'EXPLORE THE COLLECTION':'A QUESTION? LET’S TALK'}<ArrowUpRight size={17}/></OLink></Reveal></div></div></>;
};

export const Contact = () => {
  const {store}=useStore(),c=store.contact;const [form,setForm]=useState({name:'',email:'',message:'',website:''}),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);
  const submit=async e=>{e.preventDefault();setBusy(true);try{await api.post('/contact',form);setSent(true);toast.success('Your message is with our team.');}catch(err){toast.error(errorText(err));}finally{setBusy(false);}};
  return <div className="contact-page section-pad"><SEO title="A personal connection | ORYNVE"/><span className="eyebrow">CLIENT SERVICES</span><h1 className="page-title" data-testid="contact-page-title">Let’s talk.</h1><div className="contact-page-grid"><div><h2>{c.text}</h2><p>Questions about a piece, finding your fit, or something else entirely? We’re here for you.</p><div className="contact-methods">{c.whatsapp_enabled&&c.whatsapp&&<a href={`https://wa.me/${c.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" data-testid="contact-page-whatsapp">WHATSAPP<ArrowUpRight/></a>}{c.email_enabled&&c.email&&<a href={`mailto:${c.email}`} data-testid="contact-page-email">{c.email}<ArrowUpRight/></a>}{c.phone&&<a href={`tel:${c.phone}`} data-testid="contact-page-phone">{c.phone}<ArrowUpRight/></a>}</div><span className="eyebrow">OUR STUDIO</span><p>{c.address}<br/>{c.hours}</p></div>{c.form_enabled&&(sent?<div className="contact-sent" data-testid="contact-success"><Check size={36}/><h2>A good conversation starts here.</h2><p>Your message has been received. Our team will respond to the email you provided during support hours.</p><Action className="action-outline" onClick={()=>{setSent(false);setForm({name:'',email:'',message:'',website:''});}} data-testid="contact-send-another">SEND ANOTHER MESSAGE</Action></div>:<form className="contact-form" onSubmit={submit}><label>YOUR NAME<input required data-testid="contact-name" value={form.name} maxLength={120} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name"/></label><label>EMAIL ADDRESS<input type="email" required data-testid="contact-email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>YOUR MESSAGE<textarea required minLength={10} maxLength={4000} rows="5" data-testid="contact-message" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Tell us what’s on your mind…"/></label><label className="honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>setForm({...form,website:e.target.value})} data-testid="contact-website"/></label><Action disabled={busy} data-testid="contact-submit">{busy?'SENDING…':'SEND YOUR MESSAGE'}<ArrowUpRight size={17}/></Action><small>We’ll only use your information to respond to your inquiry. <OLink to="/privacy" data-testid="contact-privacy">Privacy policy.</OLink></small></form>)}</div></div>;
};

export const Maintenance = () => {
  const {store}=useStore();const [time,setTime]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setTime(Date.now()),1000);return()=>clearInterval(t);},[]);const remaining=store.maintenance.launch_date?Math.max(0,new Date(store.maintenance.launch_date).getTime()-time):0;
  return <div className="maintenance-page" data-testid="maintenance-page"><SEO title={`${store.brand.name} — ${store.site_mode==='coming_soon'?'Coming soon':'A moment of pause'}`}/><Image src={store.maintenance.image} alt="ORYNVE campaign"/><div className="maintenance-content"><span className="wordmark">{store.brand.name}</span><span className="eyebrow">{store.site_mode==='coming_soon'?'THE NEXT CHAPTER':'A MOMENT OF PAUSE'}</span><h1 data-testid="maintenance-title">{store.maintenance.title}</h1><p data-testid="maintenance-message">{store.maintenance.message}</p>{remaining>0&&<div className="countdown" data-testid="launch-countdown">{Math.floor(remaining/86400000)}D : {String(Math.floor(remaining/3600000)%24).padStart(2,'0')}H : {String(Math.floor(remaining/60000)%60).padStart(2,'0')}M</div>}{store.features.newsletter&&<Newsletter compact/>}{store.maintenance.button&&<OLink to={store.maintenance.link} className="text-link" data-testid="maintenance-contact">{store.maintenance.button}<ArrowUpRight size={16}/></OLink>}</div></div>;
};