import { useRef, useState } from 'react';
import { motion, useScroll, useTransform, useReducedMotion, AnimatePresence } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Plus } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { OLink, TextLink, Reveal, Image, SEO } from '../components/store/Common';
import { ProductCard } from '../components/store/ProductCard';
import { imgUrl } from '../lib/api';
import { useBrandEntrance } from '../components/store/BrandIntro';

const Hero = () => {
  const {store}=useStore(),h=store.hero;const ref=useRef(null);const [slide,setSlide]=useState(0);const reduced=useReducedMotion();
  const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const y=useTransform(scrollYProgress,[0,1],['0%','18%']);
  const slides=[h.image,...store.collections.slice(0,2).map(c=>c.image)].filter((x,i,a)=>x&&a.indexOf(x)===i);
  const words=h.headline.split('\n');
  return <section className="hero" ref={ref} data-testid="home-hero"><motion.div className="hero-visual" style={{y:reduced||!store.features.animations||!h.animation?0:y}}>{h.video?<video autoPlay loop muted playsInline poster={h.image} src={h.video} data-testid="hero-video" controls/>:<AnimatePresence initial={false} mode="sync"><motion.img key={slides[slide]} src={imgUrl(slides[slide],2000)} alt="ORYNVE Collection 001 — considered menswear in warm neutral tones" fetchPriority="high" className="hero-image" style={{objectPosition:h.position}} initial={{opacity:0,scale:1.035}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:reduced?0:1.1}}/></AnimatePresence>}</motion.div><div className="hero-shade" style={{'--hero-overlay':h.overlay}}/><div className="hero-grain"/><div className="hero-topline"><span className="eyebrow"><i className="small-square"/>{h.eyebrow}</span><span className="hero-edition">AN INDEPENDENT EXPRESSION</span></div><div className="hero-copy"><h1 data-testid="hero-headline">{words.map((word,i)=><span className={`hero-line ${i%2?'hero-serif':''}`} key={i}><motion.span initial={reduced||!store.features.animations?false:{y:'110%',rotate:2}} animate={{y:0,rotate:0}} transition={{duration:1.25,delay:.25+i*.15,ease:[.22,1,.36,1]}}>{word}</motion.span></span>)}</h1><motion.div initial={reduced?false:{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.7,duration:.8}} className="hero-description"><p data-testid="hero-subheadline">{h.subheadline}</p><OLink to={h.cta_link} className="hero-cta" data-testid="hero-shop-cta">{h.cta}<ArrowUpRight size={21}/></OLink><OLink to={h.secondary_link} className="hero-secondary" data-testid="hero-discover-cta">{h.secondary}<span>↗</span></OLink></motion.div></div><div className="hero-bottom"><button className="hero-scroll" onClick={()=>document.getElementById('the-edit')?.scrollIntoView({behavior:reduced?'instant':'smooth'})} data-testid="hero-scroll"><span className="scroll-line"/>SCROLL TO EXPLORE<ArrowDown size={14}/></button><span className="hero-caption">{h.caption}</span><div className="hero-pagination">{slides.map((_,i)=><button key={i} data-testid={`hero-slide-${i}`} aria-label={`Campaign image ${i+1}`} aria-pressed={slide===i} onClick={()=>setSlide(i)} className={i===slide?'active':''}>0{i+1}<span/></button>)}</div></div><span className="hero-side-note">{store.contact.address.toUpperCase()} — WORLDWIDE IN SPIRIT</span></section>;
};

const ProductSection = ({section,arrivals=false}) => {
  const {store}=useStore();const ps=arrivals?store.products.slice(-4):store.products.filter(p=>p.featured).slice(0,4);
  return <section className="product-section section-pad" id={!arrivals?'the-edit':undefined} data-testid={`section-${section.id}`}><Reveal><div className="section-kicker"><span className="eyebrow">{arrivals?'04 / NEW ARRIVALS':'01 / SELECTED PIECES'}</span><span className="eyebrow">MADE TO BECOME YOUR FAVORITES</span></div><div className="section-header"><div><h2 className="section-heading">{section.title}</h2><p>{section.subtitle}</p></div><TextLink to={arrivals?'/shop?sort=new':'/shop'} testId={`${section.id}-view-all`}>VIEW ALL PIECES</TextLink></div></Reveal><div className="product-grid">{ps.map((p,i)=><ProductCard key={p.id} product={p} index={i} prefix={section.id}/>)}</div></section>;
};

const Editorial = ({section:s}) => <section className="editorial-section" data-testid={`section-${s.id}`}><div className="editorial-image"><Image src={imgUrl(s.image,1500)} alt="Sculptural outerwear in motion — the ORYNVE philosophy" loading="lazy"/><span className="image-index">ORYNVE / A STUDY IN FORM</span></div><Reveal className="editorial-copy"><span className="eyebrow">02 / THE PHILOSOPHY</span><h2>{s.title}</h2><div className="editorial-rule"/><p>{s.subtitle}</p><TextLink to={s.link||'/about'} testId={`${s.id}-story-link`}>{s.button||'OUR PHILOSOPHY'}</TextLink><span className="editorial-footnote">LESS, BUT NEVER ORDINARY.</span></Reveal></section>;

export const LookbookSection = ({section:s,full=false}) => {
  const {store,setQuickView}=useStore();
  return <section className={`lookbook-section section-pad ${full?'lookbook-full':''}`} data-testid={`section-${s.id}`}><Reveal><div className="section-kicker"><span className="eyebrow">03 / THE CAMPAIGN</span><span className="eyebrow">{s.subtitle}</span></div><div className="section-header"><h2 className="section-heading">{s.title}</h2>{!full&&<TextLink to="/lookbook" testId={`${s.id}-lookbook-link`}>ENTER THE LOOKBOOK</TextLink>}</div></Reveal><div className="lookbook-grid">{[s.image,s.image2].filter(Boolean).map((img,i)=>{const p=store.products.find(p=>p.id===s.product_ids?.[i]);return <Reveal className={`lookbook-frame frame-${i}`} delay={i*.1} key={i}><Image src={imgUrl(img,1400)} alt={`The First Expression — campaign look ${i+1}`} loading="lazy"/><span className="lookbook-caption">FIG. 0{i+1} / {p?.name?.toUpperCase()||'THE FIRST EXPRESSION'}</span>{p&&<button className="lookbook-hotspot" onClick={()=>setQuickView(p)} aria-label={`Shop ${p.name}`} data-testid={`lookbook-hotspot-${i}`}><Plus size={20}/><span>SHOP THE LOOK</span></button>}</Reveal>;})}</div></section>;
};

const Manifesto = ({section:s}) => <section className="manifesto section-pad" data-testid={`section-${s.id}`}><Reveal><span className="eyebrow">05 / AN INDEPENDENT POINT OF VIEW</span><h2>{s.title.split('\n').map((l,i)=><span key={i} className={i?'manifesto-serif':''}>{l}</span>)}</h2><p>{s.subtitle}</p><TextLink to="/about" testId={`${s.id}-about`}>THIS IS ORYNVE</TextLink></Reveal></section>;

export default function Home(){const {store}=useStore();const entrance=useBrandEntrance();return <><SEO/><Hero key={entrance?'revealed':'waiting'}/><div className={`brand-marquee ${!store.features.animations?'no-motion':''}`} aria-hidden="true"><div>{Array.from({length:4},(_,i)=><span key={i}>INDEPENDENT IN SPIRIT <i>✳</i> CONSIDERED BY DESIGN <i>✳</i> NOT FOR EVERYONE. FOR YOU. <i>✳</i></span>)}</div></div>{store.sections.filter(s=>s.enabled).map(s=>s.type==='featured'?<ProductSection key={s.id} section={s}/>:s.type==='arrivals'?<ProductSection key={s.id} section={s} arrivals/>:s.type==='editorial'?<Editorial key={s.id} section={s}/>:s.type==='lookbook'?<LookbookSection key={s.id} section={s}/>:s.type==='manifesto'?<Manifesto key={s.id} section={s}/>:null)}</>;}