import { useEffect, useState } from 'react';
import { ArrowLeft, Plus, ArrowUpRight, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { Action } from '../../components/store/Common';
import { ObjectEditor } from './Fields';
import { api, errorText, newId, imgUrl } from '../../lib/api';

export const CollectionManager = ({store,onChange}) => {const [edit,setEdit]=useState(null);const c=store.collections.find(c=>c.id===edit);const update=c=>onChange({...store,collections:store.collections.map(x=>x.id===c.id?c:x)});if(c)return <><button className="admin-back-button" onClick={()=>setEdit(null)} data-testid="admin-collections-back"><ArrowLeft size={16}/>COLLECTIONS</button><div className="admin-section-heading"><div><h2>{c.name}</h2><p>Curate a chapter of your brand.</p></div></div><div className="admin-form-panel"><ObjectEditor value={c} onChange={update} path="edit-collection"/><h3 className="admin-panel-heading">Pieces in this collection</h3><div className="collection-product-checks">{store.products.map(p=><label key={p.id}><input type="checkbox" checked={p.collection===c.slug} onChange={e=>onChange({...store,products:store.products.map(x=>x.id===p.id?{...x,collection:e.target.checked?c.slug:''}:x)})} data-testid={`collection-product-${p.id}`}/>{p.name}</label>)}</div></div><button className="admin-delete-link" onClick={()=>{if(window.confirm('Delete this collection from the draft?')){onChange({...store,collections:store.collections.filter(x=>x.id!==c.id),products:store.products.map(p=>p.collection===c.slug?{...p,collection:''}:p)});setEdit(null);}}} data-testid="admin-collection-delete">DELETE COLLECTION</button></>;
  return <><div className="admin-section-heading"><div><h2>Chapters, not seasons.</h2><p>Reorder collections using the arrows. Assign products inside each collection.</p></div><Action onClick={()=>{const id=newId();onChange({...store,collections:[...store.collections,{id,name:'New collection',slug:'new-collection-'+id.slice(0,6),description:'',image:'',published:false}]});setEdit(id);}} data-testid="admin-add-collection"><Plus size={15}/>ADD COLLECTION</Action></div><div className="admin-collection-grid">{store.collections.map((c,i)=><div key={c.id}><button onClick={()=>setEdit(c.id)} data-testid={`admin-edit-collection-${c.id}`}><img src={imgUrl(c.image,500)} alt={c.name}/><h3>{c.name}<ArrowUpRight size={18}/></h3><span className={`status-badge ${c.published?'published':'draft'}`}>{c.published?'Published':'Draft'}</span></button><div className="admin-reorder-actions">{[-1,1].map(dir=><button key={dir} disabled={i+dir<0||i+dir>=store.collections.length} data-testid={`collection-move-${c.id}-${dir}`} onClick={()=>{const a=[...store.collections];[a[i],a[i+dir]]=[a[i+dir],a[i]];onChange({...store,collections:a});}}>{dir===-1?'← MOVE EARLIER':'MOVE LATER →'}</button>)}</div></div>)}</div></>;
};

export const PageManager = ({store,onChange}) => {const [id,setId]=useState(null);const p=store.pages.find(p=>p.id===id);return p?<><button className="admin-back-button" onClick={()=>setId(null)} data-testid="admin-pages-back"><ArrowLeft size={16}/>ALL PAGES</button><div className="admin-section-heading"><h2>{p.title}</h2></div><div className="admin-form-panel"><ObjectEditor value={p} onChange={v=>onChange({...store,pages:store.pages.map(x=>x.id===p.id?v:x)})} path="edit-page"/></div><button className="admin-delete-link" data-testid="admin-delete-page" onClick={()=>{if(window.confirm('Delete this page from the draft?')){onChange({...store,pages:store.pages.filter(x=>x.id!==id)});setId(null);}}}>DELETE PAGE</button></>:<><div className="admin-section-heading"><div><h2>Every word, considered.</h2><p>Policies, stories, and custom pages. Add links in Navigation to make new pages discoverable.</p></div><Action onClick={()=>{const id=newId();onChange({...store,pages:[...store.pages,{id,slug:'new-page-'+id.slice(0,6),title:'New page',body:'',published:false,seo_title:'',seo_description:''}]});setId(id);}} data-testid="admin-add-page"><Plus size={15}/>ADD PAGE</Action></div><div className="admin-page-list">{store.pages.map(p=><button key={p.id} onClick={()=>setId(p.id)} data-testid={`admin-edit-page-${p.slug}`}><span>{p.title}<small>/{p.slug}</small></span><span className={`status-badge ${p.published?'published':'draft'}`}>{p.published?'Published':'Draft'}</span><ArrowUpRight size={17}/></button>)}</div></>;};

export const Activity = () => {const [data,setData]=useState(null),[tab,setTab]=useState('inquiries'),[error,setError]=useState('');const load=async()=>{try{const {data}=await api.get('/admin/activity');setData(data);setError('');}catch(e){setError(errorText(e));}};useEffect(()=>{load();},[]);const setStatus=async(id,status)=>{try{await api.patch(`/admin/inquiries/${id}`,null,{params:{status}});load();toast.success('Inquiry status updated.');}catch(e){toast.error(errorText(e));}};const exportCSV=()=>{const entries=data?.[tab]||[];if(!entries.length){toast.info('No entries to export yet.');return;}const fields=tab==='subscribers'?['email','created_at']:tab==='contacts'?['name','email','message','created_at']:['id','status','total_bdt','currency','name','phone','created_at'];const escape=s=>'"'+String(s??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';const csv=[fields.join(','),...entries.map(x=>fields.map(f=>escape(x[f])).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`orynve-${tab}.csv`;a.click();URL.revokeObjectURL(url);};
  return <><div className="admin-section-heading"><div><h2>A personal connection.</h2><p>Prepared order inquiries are not confirmed sales. Follow up and update their status.</p></div><Action className="action-outline" onClick={load} data-testid="admin-activity-refresh"><RefreshCw size={14}/>REFRESH</Action></div><div className="admin-subtabs">{['inquiries','contacts','subscribers'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)} data-testid={`activity-tab-${t}`}>{t} ({data?.[t]?.length||0})</button>)}<button className="admin-export" onClick={exportCSV} data-testid="activity-export">EXPORT CSV ↗</button></div>{error&&<p className="admin-error">{error}</p>}<div className="admin-activity-list">{data?.[tab].map((entry,i)=><details key={entry.id} data-testid={`activity-entry-${i}`}><summary><span>{tab==='inquiries'?entry.id:entry.email}<small>{new Date(entry.created_at).toLocaleString()}</small></span>{tab==='inquiries'&&<span>৳{entry.total_bdt.toLocaleString()} · {entry.status}</span>}</summary><div>{tab==='inquiries'?<><pre>{entry.summary}</pre><label className="admin-field"><span>Status</span><select value={entry.status} onChange={e=>setStatus(entry.id,e.target.value)} data-testid={`inquiry-status-${entry.id}`}>{['prepared','contacted','confirmed','closed'].map(s=><option key={s}>{s}</option>)}</select></label></>:tab==='contacts'?<><strong>{entry.name}</strong><p>{entry.message}</p><a href={`mailto:${entry.email}`} className="text-link" data-testid={`reply-contact-${entry.id}`}>REPLY BY EMAIL ↗</a></>:<p>Subscribed {new Date(entry.created_at).toLocaleDateString()}</p>}</div></details>)}{data&&!data[tab].length&&<div className="admin-empty-inline">No {tab} yet. They’ll appear here as your community grows.</div>}</div></>;
};