import { useEffect, useRef, useState } from 'react';
import { Upload, Trash2, Copy, FolderOpen } from 'lucide-react';
import { toast } from 'sonner';
import { api, errorText } from '../../lib/api';
import { Action, Modal } from '../../components/store/Common';
import { Field } from './Fields';

export default function MediaManager(){const [media,setMedia]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[edit,setEdit]=useState(null),[folder,setFolder]=useState('All'),[error,setError]=useState('');const input=useRef(null);
  const load=async()=>{try{const {data}=await api.get('/admin/media');setMedia(data);setError('');}catch(e){setError(errorText(e));}};
  useEffect(()=>{load();},[]);
  const upload=async files=>{if(!files?.length)return;setBusy(true);for(const file of files){if(file.size>30*1024*1024){toast.error(`${file.name}: maximum file size is 30 MB.`);continue;}const form=new FormData();form.append('file',file);try{setProgress(0);await api.post('/admin/media',form,{onUploadProgress:e=>setProgress(Math.round(e.loaded*100/e.total))});toast.success(`${file.name} added to your library.`);}catch(e){toast.error(errorText(e));}}await load();setBusy(false);if(input.current)input.current.value='';};
  const save=async()=>{try{await api.put(`/admin/media/${edit.id}`,{name:edit.name,alt:edit.alt,focal_point:edit.focal_point,folder:edit.folder});toast.success('Media details saved.');setEdit(null);load();}catch(e){toast.error(errorText(e));}};
  const remove=async id=>{if(!window.confirm('Remove this asset from your library? Assets used by the store cannot be removed.'))return;try{await api.delete(`/admin/media/${id}`);toast.success('Media removed.');setEdit(null);load();}catch(e){toast.error(errorText(e));}};
  const copy=async url=>{try{await navigator.clipboard.writeText(url);toast.success('Media URL copied.');}catch{toast.error('Unable to access the clipboard. Open the asset and copy its URL.');}};
  return <><div className="admin-section-heading"><div><h2>The image archive.</h2><p>High-resolution assets, stored securely. JPEG, PNG, WebP, MP4 and WebM · up to 30 MB.</p></div><Action onClick={()=>input.current.click()} disabled={busy} data-testid="media-upload-button"><Upload size={15}/>{busy?`UPLOADING ${progress}%`:'UPLOAD MEDIA'}</Action><input ref={input} type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple hidden onChange={e=>upload(e.target.files)} data-testid="media-file-input"/></div><div className="media-drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)upload(e.dataTransfer.files);}} data-testid="media-drop-zone"><FolderOpen size={25}/><p>{busy?'Your images are finding their place…':'Drag your campaign images and product media here.'}</p><small>Files remain available across restarts. No temporary storage.</small></div>{error&&<p className="admin-error" data-testid="media-error">{error}</p>}<div className="admin-list-toolbar"><span>{media.length} ASSETS</span><select data-testid="media-folder-filter" value={folder} onChange={e=>setFolder(e.target.value)}>{['All',...new Set(media.map(m=>m.folder))].map(f=><option key={f}>{f}</option>)}</select></div><div className="admin-media-grid">{media.filter(m=>folder==='All'||m.folder===folder).map(m=><div className="admin-media-card" key={m.id}><button onClick={()=>setEdit(m)} data-testid={`media-edit-${m.id}`}>{m.content_type.startsWith('image/')?<img src={m.url} alt={m.alt||m.name}/>:<video src={m.url} muted preload="metadata"/>}</button><div><span>{m.name}</span><small>{m.folder} · {(m.size/1024/1024).toFixed(2)} MB</small><button aria-label="Copy media URL" data-testid={`media-copy-${m.id}`} onClick={()=>copy(m.url)}><Copy size={14}/></button></div></div>)}</div>{!media.length&&!error&&<p className="admin-empty-inline">Your library is ready for its first image. Existing campaign images use external photography URLs.</p>}<Modal open={!!edit} onOpenChange={o=>{if(!o)setEdit(null);}} title="Media details" testId="edit-media-modal">{edit&&<>{edit.content_type.startsWith('image/')&&<img className="media-edit-preview" src={edit.url} alt={edit.alt||edit.name} style={{objectPosition:edit.focal_point}}/>}{['name','alt','folder','focal_point'].map(k=><Field key={k} label={k.replace('_',' ')} value={edit[k]} onChange={v=>setEdit({...edit,[k]:v})} testId={`media-edit-${k}`}/>)}<Field label="Secure media URL" value={edit.url} readOnly onChange={()=>{}} testId="media-edit-url"/><Action onClick={save} data-testid="media-save">SAVE MEDIA DETAILS</Action><button className="admin-delete-link" onClick={()=>remove(edit.id)} data-testid="media-delete"><Trash2 size={14}/>DELETE ASSET</button></>}</Modal></>;
}