import { useState } from 'react';
import { ArrowLeft, Plus, Search, Copy, Trash2, ArrowUpRight } from 'lucide-react';
import { Action } from '../../components/store/Common';
import { newId, slugify, imgUrl } from '../../lib/api';
import { Field, ObjectEditor } from './Fields';

const tabs={Essentials:['name','slug','price','sale_price','sku','category','collection','status','featured','badge','description','tags'],Media:['images','image_alt','focal_point','video'],Variants:['sizes','colors','size_guide'],Details:['material','fit','care','shipping','returns'],SEO:['seo_title','seo_description']};
export default function ProductManager({store,onChange}){
  const [editing,setEditing]=useState(null),[tab,setTab]=useState('Essentials'),[search,setSearch]=useState(''),[status,setStatus]=useState('all');const product=store.products.find(p=>p.id===editing);
  const update=p=>onChange({...store,products:store.products.map(x=>x.id===p.id?p:x)});
  const duplicate=p=>{const copy={...structuredClone(p),id:newId(),name:p.name+' — Copy',slug:p.slug+'-copy-'+Date.now().toString().slice(-4),status:'draft',sku:p.sku+'-COPY'};onChange({...store,products:[...store.products,copy]});setEditing(copy.id);};
  const add=()=>{const id=newId();const p={id,name:'New piece',slug:'new-piece-'+id.slice(0,6),description:'',price:0,sale_price:null,sku:'',category:'Essentials',collection:store.collections[0]?.slug||'',status:'draft',featured:false,badge:'',images:[],video:'',image_alt:'',focal_point:'50% 50%',seo_title:'',seo_description:'',material:'',fit:'',care:'',shipping:'',returns:'',tags:[],colors:[{name:'Onyx',hex:'#262521'}],sizes:['XS','S','M','L','XL','XXL'].map(name=>({name,stock:0})),size_guide:{unit:'cm',labels:['Size','Chest','Length','Shoulder'],rows:[['S','','',''],['M','','',''],['L','','','']],notes:'Add verified garment measurements before publishing.'}};onChange({...store,products:[...store.products,p]});setEditing(id);setTab('Essentials');};
  const remove=p=>{if(window.confirm(`Delete “${p.name}” from the draft? The live store will not change until publishing.`)){onChange({...store,products:store.products.filter(x=>x.id!==p.id)});if(editing===p.id)setEditing(null);}};
  if(product)return <div className="admin-product-editor"><div className="admin-editor-heading"><button onClick={()=>setEditing(null)} data-testid="admin-product-back"><ArrowLeft size={16}/>ALL PRODUCTS</button><span className={`status-badge ${product.status}`}>{product.status}</span><a href={`/product/${product.slug}`} target="_blank" rel="noreferrer" data-testid="admin-product-live">LIVE PAGE<ArrowUpRight size={14}/></a></div><h2>{product.name}</h2><div className="admin-subtabs">{Object.keys(tabs).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)} data-testid={`product-editor-tab-${t.toLowerCase()}`}>{t}</button>)}</div><div className="admin-form-panel">{tab==='Essentials'?<><div className="admin-form-grid"><Field label="Product name" value={product.name} onChange={v=>update({...product,name:v})} testId="edit-product-name"/><Field label="URL slug" value={product.slug} onChange={v=>update({...product,slug:slugify(v)})} testId="edit-product-slug"/><Field label="Price (BDT)" type="number" min="0" value={product.price} onChange={v=>update({...product,price:v??0})} testId="edit-product-price"/><Field label="Sale price (BDT, optional)" type="number" min="0" value={product.sale_price} onChange={v=>update({...product,sale_price:v})} testId="edit-product-sale-price"/><Field label="Collection" value={product.collection} options={store.collections.map(c=>({value:c.slug,label:c.name}))} onChange={v=>update({...product,collection:v})} testId="edit-product-collection"/><Field label="Visibility after publishing" value={product.status} options={['draft','published','archived']} onChange={v=>update({...product,status:v})} testId="edit-product-status"/></div><ObjectEditor value={Object.fromEntries(tabs.Essentials.filter(k=>!['name','slug','price','sale_price','collection','status'].includes(k)).map(k=>[k,product[k]]))} onChange={v=>update({...product,...v})} path="edit-product"/></>:<ObjectEditor value={Object.fromEntries(tabs[tab].map(k=>[k,product[k]]))} onChange={v=>update({...product,...v})} path="edit-product"/>}</div><div className="admin-danger-actions"><button onClick={()=>duplicate(product)} data-testid="admin-product-duplicate"><Copy size={14}/>DUPLICATE AS DRAFT</button><button onClick={()=>remove(product)} data-testid="admin-product-delete"><Trash2 size={14}/>DELETE PRODUCT</button></div></div>;
  const filtered=store.products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())&&(status==='all'||p.status===status));
  return <><div className="admin-section-heading"><div><h2>The wardrobe.</h2><p>Manage your pieces. Changes stay private until published.</p></div><Action onClick={add} data-testid="admin-add-product"><Plus size={15}/>ADD PRODUCT</Action></div><div className="admin-list-toolbar"><label><Search size={16}/><input placeholder="Search products…" value={search} onChange={e=>setSearch(e.target.value)} data-testid="admin-product-search"/></label><select value={status} onChange={e=>setStatus(e.target.value)} data-testid="admin-product-status-filter"><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>PRODUCT</th><th>STATUS</th><th>INVENTORY</th><th>PRICE / BDT</th><th/></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><button className="admin-product-cell" onClick={()=>{setEditing(p.id);setTab('Essentials');}} data-testid={`admin-edit-product-${p.id}`}>{p.images[0]?<img src={imgUrl(p.images[0],160)} alt={p.name}/>:<span className="admin-media-missing">O/</span>}<span>{p.name}<small>{p.category} · {p.sku||'No SKU'}</small></span></button></td><td><span className={`status-badge ${p.status}`}>{p.status}</span></td><td>{p.sizes.reduce((a,s)=>a+s.stock,0)}<small> in stock</small></td><td>৳{p.price.toLocaleString()}</td><td><div className="admin-row-actions"><button aria-label={`Duplicate ${p.name}`} onClick={()=>duplicate(p)} data-testid={`admin-duplicate-${p.id}`}><Copy size={14}/></button><button aria-label={`Delete ${p.name}`} onClick={()=>remove(p)} data-testid={`admin-delete-${p.id}`}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="admin-empty-inline">No products match your search.</div>}</div></>;
}